apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "drupal.name" . }}
      tier: drupal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "drupal.name" . }}
        tier: drupal
    spec:
      containers:
      - image: "{{ .Values.drupal.image }}:{{ default .Chart.AppVersion .Values.drupal.tag }}"
        imagePullPolicy: {{ default "" .Values.drupal.imagePullPolicy | quote }}
        name: drupal
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "cd / && ./minio {{ .Values.minio.hostname }}"]
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "drupal.fullname" . }}
              key: password
{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 8 }}
{{- end }}
        ports:
        - containerPort: 9000
          name: drupal
        volumeMounts:
{{- if (eq "d7" .Values.drupal.version) }}
        - name: cm-drupal
          mountPath: /var/www/html/sites/default/settings.php
          subPath: d7.settings.php
{{- else }}
        - name: cm-drupal
          mountPath: /var/www/html/sites/default/settings.php
          subPath: d8.settings.php
{{- end }}
        - name: cm-minio
          mountPath: /minio
          subPath: minio
      {{- if .Values.drupal.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.drupal.imagePullSecrets | indent 8 }}
      {{- end }}
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: {{ .Values.drupal.securityContext.fsGroup }}
      volumes:
      - name: cm-drupal
        configMap:
          name: {{ include "drupal.fullname" . }}
      - name: cm-minio
        configMap:
          defaultMode: 0777
          name: {{ include "drupal.fullname" . }}-minio
