apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "drupal.fullname" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "drupal.name" . }}
      tier: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "drupal.name" . }}
        tier: db
    spec:
      containers:
      - image: "{{ .Values.mysql.image }}"
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "{{ .Values.mysql.db }}"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "drupal.fullname" . }}
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: pvc-drupal-mysql
          mountPath: /var/lib/mysql
        - name: cm-mysql
          mountPath: /etc/mysql/conf.d/overrides.cnf
          subPath: my.cnf
      {{- if .Values.mysql.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.mysql.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      - name: pvc-drupal-mysql
        persistentVolumeClaim:
          claimName: {{ include "drupal.name" . }}-mysql
      - name: cm-mysql
        configMap:
          name: {{ include "drupal.name" . }}-mysql
