apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        tier: frontend
    spec:
      containers:
      - image: "{{ .Values.nginx.image }}"
        name: nginx
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "400m"
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: cm-nginx
          subPath: nginx.conf
      {{- if .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.nginx.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      - name: cm-nginx
        configMap:
          name: {{ template "fullname" . }}-nginx
