apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "drupal.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "drupal.name" . }}
      tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "drupal.name" . }}
        tier: frontend
    spec:
      containers:
      - image: "{{ .Values.drupal.image }}:{{ default .Chart.AppVersion .Values.drupal.tag }}-nginx"
        name: nginx
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "400m"
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: cm-nginx
          readOnly: false
          subPath: nginx.conf
      {{- if .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.nginx.imagePullSecrets | indent 8 }}
      {{- end }}
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: {{ .Values.nginx.securityContext.fsGroup }}
      volumes:
      - name: cm-nginx
        configMap:
          name: {{ include "drupal.fullname" . }}-nginx
