dependencies:
  - name: mysql
    version: 1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mysql.enabled
  - name: minio
    version: 6.0.5
    repository: https://helm.min.io/
    condition: minio.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled
  - name: redis
    version: 11.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: varnish
    version: 0.0.2
    repository: https://statcan.github.io/charts
    condition: varnish.enabled
