apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.drupal.username }}
  username: {{ default "" .Values.drupal.username | b64enc | quote }}
  {{ else }}
  username: {{ "admin" | b64enc | quote }}
  {{ end }}
  {{ if .Values.drupal.password }}
  password: {{ default "" .Values.drupal.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysql.password }}
  mysql-password: {{ default "" .Values.mysql.password | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
