#
# This script is based on the https://github.com/Azure/helm-elasticstack/blob/master/.travis.yml
#
# MIT License
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

matrix:
  include:
    - language: generic
      env:
        - KUBECTL_VERSION=v1.14.1
        - HELM_VERSION=v2.13.1
      install:
        - wget https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -O /tmp/kubectl
        - chmod +x /tmp/kubectl
        - wget http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
        - tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
        - chmod +x /tmp/helm
        - export PATH=$PATH:/tmp
      before_script:
        - helm init --client-only
        - helm repo add stable https://kubernetes-charts.storage.googleapis.com
        - |
          for chart in $(find . -name 'requirements.yaml'); do
            helm dep build $(dirname ${chart})
          done
      script:
      - helm lint drupal
