name: drupal
version: 0.0.2
appVersion: 2.2.15
description: Drupal 8 variant of the Web Experience Toolkit (WxT).
keywords:
- drupal
- cms
- wxt
- http
- web
- application
- php
home: http://www.drupal.org/project/wxt
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
sources:
- https://github.com/drupalwxt/wxt
maintainers:
- name: sylus
  email: william.hearn@canada.ca
engine: gotpl
