apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drupal.fullname" . }}-minio
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  minio: |-
{{ include (print $.Template.BasePath "/_helper_extra_hosts.txt") . | indent 4 }}
