apiVersion: v1
kind: Service
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 9000
  selector:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    tier: drupal
  type:  {{ .Values.serviceType }}
