apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: {{ template "appname" . }}
    tier: frontend
  type:  {{ .Values.serviceType }}
