{{- if and .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{- if .Values.mysql.persistence.annotations }}
  annotations:
{{ toYaml .Values.mysql.persistence.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal.fullname" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}-mysql
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | quote }}
{{- if .Values.mysql.persistence.storageClass }}
{{- if (eq "-" .Values.mysql.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.mysql.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
