apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-nginx
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  storageClassName: {{ .Values.persistence.nginx.storageClassName | quote }}
  accessModes:
    - {{ .Values.persistence.nginx.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.nginx.size | quote }}
