{{- if and .Values.nginx.persistence.enabled (not .Values.nginx.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{- if .Values.nginx.persistence.annotations }}
  annotations:
{{ toYaml .Values.nginx.persistence.annotations | indent 4 }}
{{- end }}
  name: {{ template "fullname" . }}-nginx
  labels:
    app: {{ template "appname" . }}-nginx
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.nginx.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.nginx.persistence.size | quote }}
{{- if .Values.nginx.persistence.storageClass }}
{{- if (eq "-" .Values.nginx.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.nginx.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
