{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}-nginx
          servicePort: {{ .Values.servicePort }}
{{- if .Values.ingress.TLS }}
  tls:
{{ toYaml .Values.ingress.TLS | indent 4 }}
{{- end -}}
{{- end }}
