apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drupal.fullname" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "drupal.name" . }}
    helm.sh/chart: {{ include "drupal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  my.cnf: |-
    [mysqld]
    max_allowed_packet = 256M
